require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe PrinciplesController do

  def mock_principle(stubs={})
    @mock_principle ||= mock_model(Principle, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all principles as @principles" do
      Principle.stub(:all) { [mock_principle] }
      get :index
      assigns(:principles).should eq([mock_principle])
    end
  end

  describe "GET show" do
    it "assigns the requested principle as @principle" do
      Principle.stub(:find).with("37") { mock_principle }
      get :show, :id => "37"
      assigns(:principle).should be(mock_principle)
    end
  end

  describe "GET new" do
    it "assigns a new principle as @principle" do
      Principle.stub(:new) { mock_principle }
      get :new
      assigns(:principle).should be(mock_principle)
    end
  end

  describe "GET edit" do
    it "assigns the requested principle as @principle" do
      Principle.stub(:find).with("37") { mock_principle }
      get :edit, :id => "37"
      assigns(:principle).should be(mock_principle)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created principle as @principle" do
        Principle.stub(:new).with({'these' => 'params'}) { mock_principle(:save => true) }
        post :create, :principle => {'these' => 'params'}
        assigns(:principle).should be(mock_principle)
      end

      it "redirects to the created principle" do
        Principle.stub(:new) { mock_principle(:save => true) }
        post :create, :principle => {}
        response.should redirect_to(principle_url(mock_principle))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved principle as @principle" do
        Principle.stub(:new).with({'these' => 'params'}) { mock_principle(:save => false) }
        post :create, :principle => {'these' => 'params'}
        assigns(:principle).should be(mock_principle)
      end

      it "re-renders the 'new' template" do
        Principle.stub(:new) { mock_principle(:save => false) }
        post :create, :principle => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested principle" do
        Principle.stub(:find).with("37") { mock_principle }
        mock_principle.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :principle => {'these' => 'params'}
      end

      it "assigns the requested principle as @principle" do
        Principle.stub(:find) { mock_principle(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:principle).should be(mock_principle)
      end

      it "redirects to the principle" do
        Principle.stub(:find) { mock_principle(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(principle_url(mock_principle))
      end
    end

    describe "with invalid params" do
      it "assigns the principle as @principle" do
        Principle.stub(:find) { mock_principle(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:principle).should be(mock_principle)
      end

      it "re-renders the 'edit' template" do
        Principle.stub(:find) { mock_principle(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested principle" do
      Principle.stub(:find).with("37") { mock_principle }
      mock_principle.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the principles list" do
      Principle.stub(:find) { mock_principle }
      delete :destroy, :id => "1"
      response.should redirect_to(principles_url)
    end
  end

end
